# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kristi Perreault
email: kristiperreault95@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My new personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: https://kristiperreault.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kristiperreault95
github_username:  kristiperreault

# Build settings
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

navbar-links:
  Blog: "/"
  Appearances: "appearances"
  About Me: "aboutme"

avatar: "/assets/kristi.jpeg"

social-network-links:
  email: "kristiperreault95@gmail.com"
  github: kristiperreault
  twitter: kristiperreault95
  linkedin: "kristiperreault"

share-links-active:
  twitter: true
  linkedin: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
